spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:demodb
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
      encoding: UTF-8
